version: '3'
networks:
  symfony:
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-NGINX
    volumes:
      - "./symfony:/var/www/symfony"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    networks:
      - symfony
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile-PHP
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://symfony_user:symfony_password@postgresql:5432/symfony_db?serverVersion=13&charset=utf8
    depends_on:
      - postgres
    volumes:
      - "./symfony:/var/www/symfony"
    networks:
      - symfony
  postgres:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    networks:
      - symfony
