FROM php:7.4-fpm

RUN apt-get update && apt-get install -y zlib1g-dev git\
    zip \
    libpq-dev \
    libicu-dev \
    libzip-dev \
    && docker-php-ext-install opcache pdo pdo_pgsql pgsql \
    && pecl install apcu \
    && docker-php-ext-install \
        zip \
        intl
WORKDIR /var/www/symfony
RUN curl -sS https://getcomposer.org/installer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony