version: '3'
networks:
  laravel:
    driver: bridge
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: master-laravel
      MYSQL_USER: samuel
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      args:
        user: samuel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - "./src:/var/www/"
    ports:
      - "9000:9000"
    networks:
      - laravel